FROM maven:3.9.2-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY . /app
RUN mvn clean package

FROM openjdk:21-alpine
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]
